/** Auto-generated by scripts/generate-moment-excel-assets.py — do not edit by hand. */

export interface MomentEditorialRow {
  subtitle: string;
  body: string;
}

export const MOMENT_EDITORIAL: Partial<
  Record<string, Partial<Record<string, MomentEditorialRow>>>
> = {
  "blue-collar": {
    "bc-commute": {
      subtitle: "Arriving on site smoothly and ready for a physical workday",
      body: "At the start of my shift, I need to access the site quickly without searching for parking or the correct entrance. Clear directions and real‑time updates help me get to my workstation safely and on time.",
    },
    "bc-fnb": {
      subtitle: "Quick, convenient meals even during staggered or short breaks",
      body: "With short or irregular break times, I need fast access to hot meals or grab‑and‑go options, without standing in line. Automated checkout and 24/7 vending options help me eat properly and get back to work without delay.",
    },
    "bc-welcome": {
      subtitle: "Fast, secure entry and immediate orientation",
      body: "When I arrive, I must clear security checks, pick up any required gear, and find my team without confusion. I rely on simple digital check‑in, clear signage, and useful on‑site updates to start my shift efficiently.",
    },
    "bc-wellbeing": {
      subtitle: "Recover physically and mentally between demanding tasks",
      body: "After hours of manual work, I need hydration, a moment to rest, and ways to release physical tension. Simple access to physical health support, micro‑break spaces, and mental wellbeing tools helps me recharge for the rest of my shift.",
    },
    "bc-workplace": {
      subtitle: "A safe, well‑coordinated environment to perform physical tasks",
      body: "On the floor or on site, I need to know which zones are open, where to access tools, and how to report issues instantly. I want solutions that support safety, task coordination, and equipment management—without paperwork slowing me down.",
    },
  },
  "client-heal": {
    "cli-improvement": {
      subtitle: "Shaping Tomorrows Workplace",
      body: "I dedicate time each day to step back from daily operations and focus on improvement and future planning. By analyzing employee insights and team feedback, I can identify trends, highlight areas for growth, and shape strategies that strengthen both workplace and dining services.",
    },
    "cli-kickoff": {
      subtitle: "Morning KPI Touchpoint – Quick Pulse Check",
      body: "I kick off my morning with a brief but focused meeting with the Sodexo Site Manager. Together, we review the daily KPIs for both facilities and food services, using real-time dashboards from Wando that instantly highlight any priorities or service alerts that need my attention.",
    },
    "cli-lunch": {
      subtitle: "Executive Dining and Relationship Building",
      body: "In the afternoon, I dive into occupancy and usage data from Wando. This real-time information allows me to make informed adjustments to workspace layouts, cleaning schedules, and food offerings, ensuring we're always matching actual demand rather than assumptions.",
    },
    "cli-meetings": {
      subtitle: "Procurement Sync – Contract at a Glance",
      body: "Mid-morning brings my check-in with Procurement, where I confirm contract performance, review costs, and assess our sustainability metrics. Sodexo's reporting tools make this process effortless, allowing me to track compliance and value with complete confidence.",
    },
    "cli-review": {
      subtitle: "Operational Excellence Walkthrough",
      body: "Throughout the day, I stay connected with our people by reviewing our latest employee feedback and satisfaction scores. This helps me ensure that both workplace and dining services continue to evolve and align with what our employees actually need and want.",
    },
    "cli-welcome": {
      subtitle: "Arriving Onsite – A Seamless Welcome",
      body: "My day begins as I arrive at the campus, and I'm immediately reassured knowing that parking will be available, security runs efficiently, and that first essential coffee corner is ready to fuel my morning. Thanks to Sodexo's smart services, I can start my day without any stress or unexpected hurdles.",
    },
  },
  "client-learn": {
    "cli-improvement": {
      subtitle: "Shaping Tomorrows Workplace",
      body: "I dedicate time each day to step back from daily operations and focus on improvement and future planning. By analyzing employee insights and team feedback, I can identify trends, highlight areas for growth, and shape strategies that strengthen both workplace and dining services.",
    },
    "cli-kickoff": {
      subtitle: "Morning KPI Touchpoint – Quick Pulse Check",
      body: "I kick off my morning with a brief but focused meeting with the Sodexo Site Manager. Together, we review the daily KPIs for both facilities and food services, using real-time dashboards from Wando that instantly highlight any priorities or service alerts that need my attention.",
    },
    "cli-lunch": {
      subtitle: "Executive Dining and Relationship Building",
      body: "In the afternoon, I dive into occupancy and usage data from Wando. This real-time information allows me to make informed adjustments to workspace layouts, cleaning schedules, and food offerings, ensuring we're always matching actual demand rather than assumptions.",
    },
    "cli-meetings": {
      subtitle: "Procurement Sync – Contract at a Glance",
      body: "Mid-morning brings my check-in with Procurement, where I confirm contract performance, review costs, and assess our sustainability metrics. Sodexo's reporting tools make this process effortless, allowing me to track compliance and value with complete confidence.",
    },
    "cli-review": {
      subtitle: "Operational Excellence Walkthrough",
      body: "Throughout the day, I stay connected with our people by reviewing our latest employee feedback and satisfaction scores. This helps me ensure that both workplace and dining services continue to evolve and align with what our employees actually need and want.",
    },
    "cli-welcome": {
      subtitle: "Arriving Onsite – A Seamless Welcome",
      body: "My day begins as I arrive at the campus, and I'm immediately reassured knowing that parking will be available, security runs efficiently, and that first essential coffee corner is ready to fuel my morning. Thanks to Sodexo's smart services, I can start my day without any stress or unexpected hurdles.",
    },
  },
  "client-play": {
    "cli-improvement": {
      subtitle: "Shaping Tomorrows Workplace",
      body: "I dedicate time each day to step back from daily operations and focus on improvement and future planning. By analyzing employee insights and team feedback, I can identify trends, highlight areas for growth, and shape strategies that strengthen both workplace and dining services.",
    },
    "cli-kickoff": {
      subtitle: "Morning KPI Touchpoint – Quick Pulse Check",
      body: "I kick off my morning with a brief but focused meeting with the Sodexo Site Manager. Together, we review the daily KPIs for both facilities and food services, using real-time dashboards from Wando that instantly highlight any priorities or service alerts that need my attention.",
    },
    "cli-lunch": {
      subtitle: "Executive Dining and Relationship Building",
      body: "In the afternoon, I dive into occupancy and usage data from Wando. This real-time information allows me to make informed adjustments to workspace layouts, cleaning schedules, and food offerings, ensuring we're always matching actual demand rather than assumptions.",
    },
    "cli-meetings": {
      subtitle: "Procurement Sync – Contract at a Glance",
      body: "Mid-morning brings my check-in with Procurement, where I confirm contract performance, review costs, and assess our sustainability metrics. Sodexo's reporting tools make this process effortless, allowing me to track compliance and value with complete confidence.",
    },
    "cli-review": {
      subtitle: "Operational Excellence Walkthrough",
      body: "Throughout the day, I stay connected with our people by reviewing our latest employee feedback and satisfaction scores. This helps me ensure that both workplace and dining services continue to evolve and align with what our employees actually need and want.",
    },
    "cli-welcome": {
      subtitle: "Arriving Onsite – A Seamless Welcome",
      body: "My day begins as I arrive at the campus, and I'm immediately reassured knowing that parking will be available, security runs efficiently, and that first essential coffee corner is ready to fuel my morning. Thanks to Sodexo's smart services, I can start my day without any stress or unexpected hurdles.",
    },
  },
  "client-work": {
    "cli-improvement": {
      subtitle: "Shaping Tomorrows Workplace",
      body: "I dedicate time each day to step back from daily operations and focus on improvement and future planning. By analyzing employee insights and team feedback, I can identify trends, highlight areas for growth, and shape strategies that strengthen both workplace and dining services.",
    },
    "cli-kickoff": {
      subtitle: "Morning KPI Touchpoint – Quick Pulse Check",
      body: "I kick off my morning with a brief but focused meeting with the Sodexo Site Manager. Together, we review the daily KPIs for both facilities and food services, using real-time dashboards from Wando that instantly highlight any priorities or service alerts that need my attention.",
    },
    "cli-lunch": {
      subtitle: "Executive Dining and Relationship Building",
      body: "In the afternoon, I dive into occupancy and usage data from Wando. This real-time information allows me to make informed adjustments to workspace layouts, cleaning schedules, and food offerings, ensuring we're always matching actual demand rather than assumptions.",
    },
    "cli-meetings": {
      subtitle: "Procurement Sync – Contract at a Glance",
      body: "Mid-morning brings my check-in with Procurement, where I confirm contract performance, review costs, and assess our sustainability metrics. Sodexo's reporting tools make this process effortless, allowing me to track compliance and value with complete confidence.",
    },
    "cli-review": {
      subtitle: "Operational Excellence Walkthrough",
      body: "Throughout the day, I stay connected with our people by reviewing our latest employee feedback and satisfaction scores. This helps me ensure that both workplace and dining services continue to evolve and align with what our employees actually need and want.",
    },
    "cli-welcome": {
      subtitle: "Arriving Onsite – A Seamless Welcome",
      body: "My day begins as I arrive at the campus, and I'm immediately reassured knowing that parking will be available, security runs efficiently, and that first essential coffee corner is ready to fuel my morning. Thanks to Sodexo's smart services, I can start my day without any stress or unexpected hurdles.",
    },
  },
  "doctor": {
    "doc-break": {
      subtitle: "Short, restorative pauses to protect my mental and physical health",
      body: "On busy days, I want my breaks to really help me reset—physically and mentally. I need easy access to healthy snacks, hydration, movement and mental health support so that even a few minutes away from the ward help me recover and sustain high‑quality care.",
    },
    "doc-commute": {
      subtitle: "Effortless, predictable commute before starting rounds",
      body: "I want to arrive calmly and on time, without worrying about parking constraints or navigating a complex hospital campus. I need guided directions from home to my spot and a smooth digital entry so I can focus on my first patients rather than logistics.",
    },
    "doc-consult": {
      subtitle: "Instant access to clinical spaces, data and support services",
      body: "During my shift, I need efficient workflows that reduce friction: finding rooms, retrieving real‑time data, and triggering service tasks quickly. Reliable systems must help me focus on patient care rather than operational hurdles.",
    },
    "doc-end-shift": {
      subtitle: "Smooth closure of the day and feedback for continuous improvement",
      body: "At the end of my shift, I want a simple way to share feedback and know that my experience contributes to better care and operations. I need tools that capture my insights, track sustainability impacts and support my mental decompression as I transition out of clinical mode.",
    },
    "doc-fnb": {
      subtitle: "Quick, healthy refueling in a high‑pressure clinical schedule",
      body: "Between consultations and rounds, I want to grab something to eat without waiting in long queues or compromising on nutrition. I need smart, automated food services that are fast, safe and varied, so I can refuel and get back to my patients on time.",
    },
    "doc-meetings": {
      subtitle: "Smooth coordination and shared visibility across the care team",
      body: "When collaborating with colleagues, I want to find an available room quickly and start on time without technical friction. I need easy room booking, clear displays and fast service support so we can concentrate on patients, outcomes and care coordination.",
    },
    "doc-rounds": {
      subtitle: "Patient follow-up & Administrative tasks",
      body: "During rounds, I want information, spaces and equipment to be ready when I arrive in each room. I need real‑time operational data, reliable food safety and quality tracking, and flexible room management so I can move efficiently from patient to patient without delays.",
    },
  },
  "grey-collar": {
    "gc-commute": {
      subtitle: "Getting to the facility efficiently and ready for a technical day",
      body: "Before my shift or research cycle begins, I need a smooth trip to the site with clear guidance on parking and building access. Reliable navigation helps me arrive on time so I can focus on technical tasks—not logistics.",
    },
    "gc-fnb": {
      subtitle: "Recovering and staying connected during demanding technical cycles",
      body: "After long hours of lab work or production monitoring, I need short, restorative breaks and easy access to hydration or mental wellbeing resources. Staying connected to colleagues—across shifts or sites—helps maintain a healthy rhythm.",
    },
    "gc-welcome": {
      subtitle: "Quick site access and immediate lab/tech‑floor orientation",
      body: "When I arrive, I need fast badge access, information on lab availability, and immediate visibility on any safety or equipment notices. Digital reception and clear displays help me get to the right zone without delays.",
    },
    "gc-wellbeing": {
      subtitle: "Fast and reliable meals that fit unpredictable schedules",
      body: "My break times aren’t always regular, so I need food options I can access quickly—whether a full meal or a smart‑vending solution. Automated checkout and personalized options help me refuel efficiently before heading back to the lab or floor.",
    },
    "gc-workplace": {
      subtitle: "A controlled, safe, and well‑orchestrated technical environment",
      body: "During experiments or technical operations, I rely on equipment, rooms, and safety systems functioning as expected. Automated monitoring, alerts, and streamlined work orders let me concentrate on my tasks without manually checking every device.",
    },
  },
  "military": {
    "mil-after-work": {
      subtitle: "Debriefing & Physical training",
      body: "After operations, I conduct debriefing sessions to review performance and lessons learned. Then I hit the gym for physical training—maintaining fitness is non-negotiable. I need structured routines that support both mental sharpness and physical readiness.",
    },
    "mil-diner": {
      subtitle: "Personal time & Preparation for next day",
      body: "Back in my quarters, I review tomorrow's schedule, respond to emails, and decompress. The transition from duty to personal time is essential. I need moments of calm to maintain work-life balance despite the demanding nature of military service.",
    },
    "mil-evening": {
      subtitle: "Personal time & Preparation for next day",
      body: "Back in my quarters, I review tomorrow's schedule, respond to emails, and decompress. The transition from duty to personal time is essential. I need moments of calm to maintain work-life balance despite the demanding nature of military service.",
    },
    "mil-lunch": {
      subtitle: "Mess hall dining & Networking",
      body: "Lunchtime at the mess hall is both nourishment and networking. I eat with fellow officers, discussing strategy and building camaraderie. I need quality food that fuels performance and a space that fosters meaningful professional interactions and team cohesion.",
    },
    "mil-morning": {
      subtitle: "Base arrival & Morning briefing",
      body: "I arrive on base early, in uniform, ready for the day's operations. The morning briefing sets the tone—mission updates, personnel assignments, readiness checks. I need clear directives and situational awareness to lead my team effectively throughout the day.",
    },
    "mil-work": {
      subtitle: "Operations & Training exercises",
      body: "My day involves strategic planning sessions, overseeing logistics, and leading training exercises. I balance administrative duties with hands-on leadership, ensuring my team is prepared and mission-ready. I need efficiency and precision in every task to maintain operational excellence.",
    },
  },
  "nurse": {
    "nur-break": {
      subtitle: "Micro‑breaks that genuinely help me recover",
      body: "On intense days, I want short breaks that really help me breathe and reset. I need quiet spaces, support for mental and physical health, healthy snacks and hydration options so that even a few minutes away from the ward make a positive difference.",
    },
    "nur-care": {
      subtitle: "Patient care rounds & Medication administration",
      body: "Throughout my shift, I move between patient rooms—administering medications, monitoring vitals, providing comfort, and coordinating with doctors. I need smart room booking, real‑time operational insights, quality and food safety tools, and easy service requests so we can provide safe, consistent care as a team.",
    },
    "nur-commute": {
      subtitle: "Reliable, low‑stress journey before a demanding shift",
      body: "Before a long shift, I want to arrive without stress from traffic, parking or hospital navigation. I need clear wayfinding, easy access to parking and a quick digital check‑in so I can start focused on my patients, not on the commute.",
    },
    "nur-fnb": {
      subtitle: "Quick meal break & Recharge moment",
      body: "Breaks are short and unpredictable—I grab a quick meal when patient care allows. I need fast, nourishing options that give me energy to sustain focus and compassion through long, demanding shifts. A moment to recharge makes all the difference.",
    },
    "nur-freetime": {
      subtitle: "Supporting my life balance beyond the hospital walls",
      body: "Outside of shifts, I want tools that support my overall wellbeing and help me feel valued. I need easy ways to access wellbeing services, stay active, share feedback and adopt sustainable habits so that my work and personal life feel more balanced.",
    },
    "nur-welcome": {
      subtitle: "Smooth start of shift with clear information and handover",
      body: "When I arrive on site, I want to understand instantly what’s happening on the ward today. I need clear digital reception, up‑to‑date information displays, training and work order tools so that I’m aligned on priorities from the very first minutes.",
    },
  },
  "operator-heal": {
    "op-fm-round": {
      subtitle: "Operational Monitoring & Quality Control",
      body: "I then head to the kitchen and back areas for an inspection. I check cleanliness, equipment, and compliance with hygiene and safety standards. I also take the opportunity to talk with my teams, listen to their feedback, and solve any issues they raise.",
    },
    "op-food-service": {
      subtitle: "Peak Operations & Crisis Management",
      body: "Lunch is one of the most important moments of the day. I’m present in the dining area to ensure everything goes as planned: the food is high quality, service is smooth, and guests are satisfied. It’s also when I can directly observe my teams in action and spot opportunities for improvement.",
    },
    "op-kick-off": {
      subtitle: "Team Coordination & Priority Setting",
      body: "I start the morning with a quick team briefing. This kick-off is key to align everyone on the day’s priorities and responsibilities. After that, I carry out my early checks to make sure everything is running smoothly, safe, and ready for operations.",
    },
    "op-office-time": {
      subtitle: "Administrative Tasks & Performance Review",
      body: "In my office, I focus on more strategic tasks: reviewing performance indicators, preparing reports, answering emails, and staying connected with clients. I also analyze data and look for ways to improve efficiency and the quality of service.",
    },
    "op-order-planning": {
      subtitle: "Strategic Planning & Continuous Improvement",
      body: "Part of my role is to keep everything coordinated. I manage orders, oversee planning, and make sure maintenance activities are scheduled and followed through. I anticipate future needs and work with suppliers and partners to avoid disruptions.",
    },
  },
  "operator-learn": {
    "op-fm-round": {
      subtitle: "Operational Monitoring & Quality Control",
      body: "I then head to the kitchen and back areas for an inspection. I check cleanliness, equipment, and compliance with hygiene and safety standards. I also take the opportunity to talk with my teams, listen to their feedback, and solve any issues they raise.",
    },
    "op-food-service": {
      subtitle: "Peak Operations & Crisis Management",
      body: "Lunch is one of the most important moments of the day. I’m present in the dining area to ensure everything goes as planned: the food is high quality, service is smooth, and guests are satisfied. It’s also when I can directly observe my teams in action and spot opportunities for improvement.",
    },
    "op-kick-off": {
      subtitle: "Team Coordination & Priority Setting",
      body: "I start the morning with a quick team briefing. This kick-off is key to align everyone on the day’s priorities and responsibilities. After that, I carry out my early checks to make sure everything is running smoothly, safe, and ready for operations.",
    },
    "op-office-time": {
      subtitle: "Administrative Tasks & Performance Review",
      body: "In my office, I focus on more strategic tasks: reviewing performance indicators, preparing reports, answering emails, and staying connected with clients. I also analyze data and look for ways to improve efficiency and the quality of service.",
    },
    "op-order-planning": {
      subtitle: "Strategic Planning & Continuous Improvement",
      body: "Part of my role is to keep everything coordinated. I manage orders, oversee planning, and make sure maintenance activities are scheduled and followed through. I anticipate future needs and work with suppliers and partners to avoid disruptions.",
    },
  },
  "operator-play": {
    "op-fm-round": {
      subtitle: "Operational Monitoring & Quality Control",
      body: "I then head to the kitchen and back areas for an inspection. I check cleanliness, equipment, and compliance with hygiene and safety standards. I also take the opportunity to talk with my teams, listen to their feedback, and solve any issues they raise.",
    },
    "op-food-service": {
      subtitle: "Peak Operations & Crisis Management",
      body: "Lunch is one of the most important moments of the day. I’m present in the dining area to ensure everything goes as planned: the food is high quality, service is smooth, and guests are satisfied. It’s also when I can directly observe my teams in action and spot opportunities for improvement.",
    },
    "op-kick-off": {
      subtitle: "Team Coordination & Priority Setting",
      body: "I start the morning with a quick team briefing. This kick-off is key to align everyone on the day’s priorities and responsibilities. After that, I carry out my early checks to make sure everything is running smoothly, safe, and ready for operations.",
    },
    "op-office-time": {
      subtitle: "Administrative Tasks & Performance Review",
      body: "In my office, I focus on more strategic tasks: reviewing performance indicators, preparing reports, answering emails, and staying connected with clients. I also analyze data and look for ways to improve efficiency and the quality of service.",
    },
    "op-order-planning": {
      subtitle: "Strategic Planning & Continuous Improvement",
      body: "Part of my role is to keep everything coordinated. I manage orders, oversee planning, and make sure maintenance activities are scheduled and followed through. I anticipate future needs and work with suppliers and partners to avoid disruptions.",
    },
  },
  "operator-work": {
    "op-fm-round": {
      subtitle: "Operational Monitoring & Quality Control",
      body: "I then head to the kitchen and back areas for an inspection. I check cleanliness, equipment, and compliance with hygiene and safety standards. I also take the opportunity to talk with my teams, listen to their feedback, and solve any issues they raise.",
    },
    "op-food-service": {
      subtitle: "Peak Operations & Crisis Management",
      body: "Lunch is one of the most important moments of the day. I’m present in the dining area to ensure everything goes as planned: the food is high quality, service is smooth, and guests are satisfied. It’s also when I can directly observe my teams in action and spot opportunities for improvement.",
    },
    "op-kick-off": {
      subtitle: "Team Coordination & Priority Setting",
      body: "I start the morning with a quick team briefing. This kick-off is key to align everyone on the day’s priorities and responsibilities. After that, I carry out my early checks to make sure everything is running smoothly, safe, and ready for operations.",
    },
    "op-office-time": {
      subtitle: "Administrative Tasks & Performance Review",
      body: "In my office, I focus on more strategic tasks: reviewing performance indicators, preparing reports, answering emails, and staying connected with clients. I also analyze data and look for ways to improve efficiency and the quality of service.",
    },
    "op-order-planning": {
      subtitle: "Strategic Planning & Continuous Improvement",
      body: "Part of my role is to keep everything coordinated. I manage orders, oversee planning, and make sure maintenance activities are scheduled and followed through. I anticipate future needs and work with suppliers and partners to avoid disruptions.",
    },
  },
  "parent": {
    "lp-evening": {
      subtitle: "Review & Planning Ahead",
      body: "In the evening, I want tools and gentle nudges that help me understand my child’s day, manage small needs and maintain a healthy family rhythm. Simple digital touchpoints for hydration, wellbeing and feedback support a smooth close to the day.",
    },
    "lp-meals": {
      subtitle: "Transparent, trustworthy insights into what my child eats",
      body: "I want clear, easy‑to‑access visibility on menus, nutritional details, allergens and sustainability practices. This helps me feel reassured about my child’s wellbeing and eating habits, while supporting the school’s commitment to healthy and responsible food services.",
    },
    "lp-pickup": {
      subtitle: "After-School Coordination",
      body: "When I arrive to pick up my child, I need clear directions, simple check‑out processes and a smooth flow through the school campus. Digital reception, signage and access control systems help ensure safety, reduce waiting, and make this moment feel calm and positive.",
    },
    "lp-prep": {
      subtitle: "Coordinating Family Logistics",
      body: "Before bringing my child to school, I want clear routes, predictable timing and quick access to essential digital information. When mobility, parking and wayfinding feel reliable, the morning routine becomes lighter — reducing stress for me and setting a calm tone for my child.",
    },
    "lp-school": {
      subtitle: "Peace of mind through real‑time visibility and responsive support",
      body: "Throughout the day, I want to know that my child is safe and everything is running smoothly. Real‑time updates, simple communication channels and quick service escalation options help me stay informed without being intrusive, creating a quiet sense of trust in the school’s operations.",
    },
    "lp-weekly": {
      subtitle: "Meal Planning & Logistics Management",
      body: "Each week, I need an organized view of menus, schedules and key school information. Digital planning tools make it easy to anticipate, adjust and stay aligned with the school’s rhythm, reducing mental load and helping the entire family stay coordinated.",
    },
  },
  "participant": {
    "par-after": {
      subtitle: "A smooth, thoughtful close to the day that reinforces the event’s impact",
      body: "When everything wraps up, I need help leaving efficiently, along with ways to share impressions while they’re still fresh. Guidance, sustainability cues and post‑event digital touchpoints help transition smoothly from the immersive energy of the show back to everyday life—while keeping the positive emotions alive.",
    },
    "par-arrival": {
      subtitle: "A welcoming, intuitive entry that sets the tone for the whole experience",
      body: "As soon as I reach the venue, I expect a fast, well-orchestrated welcome—clear signage, quick digital check-in, and accessible assistance when needed. This first touchpoint shapes my perception of the event, helping me feel expected, supported and ready to explore confidently.",
    },
    "par-commute": {
      subtitle: "A guided, stress‑free journey that builds anticipation",
      body: "Before arriving at the venue, I want a commute that feels simple and enjoyable, with clear directions, real‑time updates and smooth parking or drop-off options. This helps me enter the mindset of discovery and excitement instead of worrying about logistics or delays.",
    },
    "par-nav": {
      subtitle: "A fluid, self-directed exploration of stages, stands and experiences",
      body: "Once inside, I want to move effortlessly between spaces—finding my favorite sessions, discovering new attractions, and orienting myself without friction. Real-time wayfinding, occupancy insights and digital cues transform the venue into a landscape I can explore at my own pace, without missing key moments.",
    },
    "par-net": {
      subtitle: "Meaningful interactions supported by convenient, energizing refreshments",
      body: "Between sessions, I want places to meet people, recharge mentally and grab something quick but healthy. Whether I need hydration, a light snack or a full break, smart vending, innovative F&B and mobile-friendly services keep me energized and open to spontaneous conversations that enrich the event.",
    },
    "par-talk": {
      subtitle: "Immersive, accessible sessions that engage me fully",
      body: "During a keynote or demo, I want high‑quality displays, smooth tech, and ways to react instantly—whether sharing feedback, accessing extra content, or bookmarking what interests me. This makes every talk more interactive, memorable and aligned with my personal journey through the event.",
    },
  },
  "patient": {
    "pat-admission": {
      subtitle: "Reassuring, well‑orchestrated arrival and check‑in",
      body: "When I enter the hospital, I want to feel welcomed and informed rather than overwhelmed. I need intuitive digital admission, clear signage and displays, smooth access control and support services so that my first impression is one of safety and care.",
    },
    "pat-care": {
      subtitle: "Quick refreshment between appointments",
      body: "Throughout my stay, I want to understand what’s happening around me and feel that my environment is safe and well managed. I need connected equipment, clean and comfortable spaces, monitored air quality and food safety, along with smooth coordination between staff and services.",
    },
    "pat-commute": {
      subtitle: "Guided, less‑stress journey to the hospital",
      body: "On the way to the hospital, I want to know exactly where to go and where to park so I don’t arrive anxious or late. I need clear directions, accessible parking and digital reception that reassures me I’m in the right place.",
    },
    "pat-leave": {
      subtitle: "Clear, positive transition from hospital to home",
      body: "When I leave the hospital, I want the process to be simple, with space to share my experience and understand the impact of my stay. I need easy feedback tools, clear digital guidance and visible sustainable practices so that my discharge feels structured, respectful and future‑oriented.",
    },
    "pat-lunch": {
      subtitle: "Safe, personalized lunch experience in hospital",
      body: "At lunchtime, I want my meal to arrive on time, match my dietary constraints and be easy to consume in my room or a dedicated space. I need reliable food delivery, automated checks, feedback options and responsible waste handling so I feel respected as both a patient and a person.",
    },
    "pat-rest": {
      subtitle: "Feeling safe, calm and supported throughout recovery",
      body: "During quiet moments between care activities, I want to rest peacefully, clear my mind and regain a sense of balance. I need a comfortable, healthy environment with good air quality, hydration options, light movement opportunities and emotional support—so that every pause contributes to my healing, not just my waiting time.",
    },
    "pat-snack": {
      subtitle: "Simple, healthy snack moments between meals",
      body: "Between main meals, I want to access small snacks or drinks that fit my treatment and preferences. I need easy‑to‑use machines and options that feel healthy and safe, without having to walk far or wait in line.",
    },
  },
  "schoolchild": {
    "sch-class": {
      subtitle: "Classroom Engagement & Focus Management",
      body: "In class, I need clean air, clear information displays, and tools that help my teacher keep everything running smoothly. Smart digital systems support a calm, focused atmosphere where I can concentrate, ask questions and enjoy learning without distractions.",
    },
    "sch-commute": {
      subtitle: "Morning Prep & Getting Organized",
      body: "On my way to school, I need clear direction and simple digital cues that help me arrive safely and confidently. When the route feels predictable and engaging, it reduces stress and makes the start of the day calmer for everyone.",
    },
    "sch-fnb": {
      subtitle: "Lunch Break & Peer Time",
      body: "At lunchtime, I want to eat quickly so I have more time to play or hang out with friends. I struggle with long queues and confusing meal options, so I need simple food that’s quick to access, tasty and in line with what kids enjoy — but always safe and responsibly managed.",
    },
    "sch-freetime": {
      subtitle: "After School & Homework Management",
      body: "During recess or after class, I want space to move, play, snack and hydrate. Gentle sustainable nudges and healthy choices help me stay active and refreshed, so I can return to learning with energy and enthusiasm.",
    },
    "sch-welcome": {
      subtitle: "Arrival & Social Connection",
      body: "When I step into school, I want to feel welcomed, guided and supported. Clear signage, friendly digital reception and sustainable cues help me settle into the environment, feel safe, and know exactly where to go without confusion.",
    },
  },
  "senior": {
    "sen-activities": {
      subtitle: "Group activities & Personal time",
      body: "During the day, I want activities that keep me active, stimulated and socially connected. I have options—art therapy, gentle exercise or quiet reading. I need clear information on what’s happening, gentle support for physical and mental health, and programs that make me feel useful and included in a sustainable community.",
    },
    "sen-break": {
      subtitle: "Quiet moments to rest and breathe during the day",
      body: "Between activities, I want calm spaces to rest, have a drink or a snack, and feel the air is fresh and healthy. I need simple access to hydration, light exercise, mental health support and sustainable amenities to feel cared for in every detail.",
    },
    "sen-breakfast": {
      subtitle: "Safe, tailored meals to start the day with confidence",
      body: "In the morning, I want a breakfast that fits my tastes and dietary needs, without worrying about safety or long waits. I need varied, personalized options, hydration solutions and smart, assisted serving so eating remains a pleasant and reassuring moment.",
    },
    "sen-dinner": {
      subtitle: "Evening meal & Reflection",
      body: "Dinner is lighter and more relaxed. I unwind with fellow residents, reflecting on the day. I need this routine to feel comforting and familiar, a gentle transition toward evening that respects my independence and provides warmth as the day closes.",
    },
    "sen-lunch": {
      subtitle: "Comforting, well‑managed meals in a protected setting",
      body: "At lunchtime, I want to enjoy my meal without rushing, confusion or fear of mistakes in my diet. I need safe food preparation, assistance where needed, flexible serving options and responsible waste handling so mealtimes stay a highlight of my day.",
    },
    "sen-welcome": {
      subtitle: "Warm, reassuring arrival in a new care environment",
      body: "When I arrive as a resident, I want to feel expected, guided and safe—not lost in a complex building. I need accessible digital reception, clear displays, simple wayfinding and assisted communication so I can find my room and understand what will happen next.",
    },
  },
  "sport-fan": {
    "sf-after": {
      subtitle: "Smooth, clean and positive end‑of‑game transition",
      body: "When the match ends, I want to leave the stadium safely, efficiently and with a good final impression. I need simple feedback tools, visible sustainable waste handling and clear digital guidance that help manage crowds and support an environmentally responsible exit.",
    },
    "sf-commute": {
      subtitle: "Smooth, straightforward journey to the stadium",
      body: "Before the event, I want to arrive without stress caused by traffic, parking uncertainty or navigating a crowded venue. I need clear guidance, easy access to parking and seamless digital touchpoints so I can focus on enjoying the match from the moment I leave home.",
    },
    "sf-halftime": {
      subtitle: "Quick, dynamic break without losing the momentum",
      body: "At halftime, I want to refresh myself and explore entertainment options without rushing. I need fast-access vending, robotic support, circular economy touchpoints, and smart drink experiences so I can enjoy the break and return to my seat on time.",
    },
    "sf-match": {
      subtitle: "Immersive and connected live game experience",
      body: "During the match, I want to stay focused on the action without missing key moments for snacks or drinks. I need fast delivery options, frictionless checkout, and access to fan merchandise or refreshments through smart micro‑markets—everything enhancing the game, not interrupting it.",
    },
    "sf-waiting": {
      subtitle: "Enjoyable, engaging pre‑match moments",
      body: "While waiting for kick‑off, I want to explore, grab a drink, check stats and share the hype with friends—without queues or friction. I need convenient automated food & beverage options, fast service and digital experiences that keep me entertained until the action begins.",
    },
    "sf-welcome": {
      subtitle: "Fast, intuitive arrival experience that sets the tone",
      body: "When I reach the stadium, I want to get in quickly, understand where I need to go, and immediately feel the excitement building. I need efficient digital reception, visible signage, sustainability cues and charging options so the entrance feels smooth, modern and fan‑friendly.",
    },
  },
  "student": {
    "stu-commute": {
      subtitle: "Travel Juggling & Productive Day Preparation",
      body: "Before reaching campus, I want clear guidance, easy mobility options and the ability to charge my devices on the go. A fluid commute helps me arrive ready, calm and mentally aligned with my study goals.",
    },
    "stu-fnb": {
      subtitle: "Smart Payment, Personalized Dining & Loyalty Experience",
      body: "At lunchtime, I head to the cafeteria looking for my go-to healthy options without endless queues. I need to fuel up efficiently before afternoon calls, so I want a streamlined payment process that remembers my food preferences automatically without repeatedly inputting details.",
    },
    "stu-freetime": {
      subtitle: "Wellbeing routine and socialization",
      body: "During downtime, I want places to relax, hydrate, move or take a moment to decompress. Wellbeing cues and circular initiatives help create a healthy balance, ensuring I return to my studies refreshed, not drained.",
    },
    "stu-studies": {
      subtitle: "Focused Learning & Space Hunting",
      body: "Throughout my study sessions, I want access to clean, well‑air‑circulated spaces, real-time room availability, and digital tools that help me focus. Service requests, IoT data and space analytics ensure that the environment supports productivity rather than creating friction.",
    },
    "stu-welcome": {
      subtitle: "Campus Orientation & Early Morning Fuel",
      body: "When I arrive, I expect quick orientation, digital check‑ins, sustainability cues and an environment that feels inclusive and dynamic. Displays, guidance systems and concierge-like support help me transition smoothly into the rhythm of the day.",
    },
  },
  "teacher": {
    "tea-arrival": {
      subtitle: "Morning Setup & Student Check-In",
      body: "When I arrive, I want quick access to essential information, smooth navigation through the campus, and tools that help me prepare my classroom. I want my students to feel welcomed and ready to learn, so I use integrated digital tools to quickly assess who might need extra attention or resources before class begins.",
    },
    "tea-commute": {
      subtitle: "A calm, predictable commute",
      body: "Before entering school, I need a journey that feels reliable — intuitive parking, clear wayfinding and simple digital guidance. A smooth commute allows me to mentally shift into educator mode and arrive grounded, organized, and ready to support my students.",
    },
    "tea-fnb": {
      subtitle: "Efficient Break & Colleague Connection",
      body: "During lunch, I grab a quick meal while potentially supervising students or attending meetings. I need efficient access to quality food without long waits, and I value time to collaborate with colleagues about student wellness and share observations from my dashboard about at-risk students.",
    },
    "tea-freetime": {
      subtitle: "Administrative Tasks & Professional Development",
      body: "After an intense stretch of teaching, I need short breaks that truly restore me: hydration, movement, mental decompression or simply a quiet moment. Wellbeing solutions help me sustain energy and patience throughout the day, supporting both my performance and my long-term resilience.",
    },
    "tea-teaching": {
      subtitle: "Teaching & Student Support Balance",
      body: "During lessons, I need dependable digital tools, good air quality, clear displays, and immediate support when something goes wrong. Automation, booking systems and IoT insights help maintain a calm, productive environment where students can concentrate and creativity can flourish.",
    },
  },
  "tourist": {
    "tou-commute": {
      subtitle: "A smooth, personalized journey that sets the tone for an elevated travel experience",
      body: "Before reaching the airport, I expect a seamless and dignified start to my trip. Clear navigation, premium parking options, and concierge‑assisted mobility help me avoid common travel stressors. Every touchpoint—from routing to digital guidance—should feel intentional, calming, and worthy of a VIP traveler.",
    },
    "tou-depart": {
      subtitle: "A guided, efficient transition from lounge to aircraft without stress",
      body: "When it’s time to board, I want clear, real‑time guidance showing the fastest route, gate information updates and battery support along the way. A seamless passage to the aircraft maintains the sense of privilege and calm that defines the VIP experience.",
    },
    "tou-eat": {
      subtitle: "A refined culinary moment that blends convenience, personalization and pleasure",
      body: "Before boarding, I want to enjoy elevated food options, whether curated beverages, healthy alternatives or quick signature dishes. Innovative vending, robots and intelligent tray scanning make high‑quality refreshments instantly accessible without sacrificing elegance or efficiency.",
    },
    "tou-visit": {
      subtitle: "A serene, well‑equipped space to connect, focus or unwind before departure",
      body: "While waiting, I want access to quiet work areas, premium air quality, responsive services, and effortless room booking when necessary. Digital systems providing real‑time insights, hydration options and service requests ensure that every minute feels comfortable, productive and tailored to my needs.",
    },
    "tou-welcome": {
      subtitle: "An elegant, fast‑track entry designed to remove every friction",
      body: "Upon arrival, I want an exclusive welcome: swift security pathways, effortless digital check‑in, and clear directions to lounges or dedicated zones. High‑quality displays, sustainability cues and concierge presence create a refined, reassuring environment that makes the transition from outside to airside fluid and premium.",
    },
  },
  "vip-guest": {
    "vip-after": {
      subtitle: "A graceful, well‑supported departure that closes the experience on a high note",
      body: "As the night ends, I want help navigating exits, retrieving services and giving quick feedback while avoiding the crowds. Circular systems, concierge support and digital guidance ensure that even the last moments feel curated and calm — reinforcing the value of the VIP journey from start to finish.",
    },
    "vip-arrival": {
      subtitle: "A refined, hospitality‑centric welcome worthy of a premium guest",
      body: "Upon reaching the stadium, I expect an exclusive arrival flow with prioritized access, effortless check‑in and immediate orientation. Digital reception, elegant signage and attentive services ensure that I transition from outside to inside without waiting, friction, or uncertainty — strengthening the feeling of being genuinely valued.",
    },
    "vip-commute": {
      subtitle: "A smooth, privileged journey that sets the tone for an exclusive experience",
      body: "As a VIP guest, I want my arrival to feel effortless and elevated — from premium parking access to curated guidance that shortens the distance between me and the event. Optimized routing, concierge‑level support and clear digital cues help transform the commute into the first touchpoint of a seamless luxury experience.",
    },
    "vip-eat": {
      subtitle: "A premium food experience that balances exclusivity, convenience and delight",
      body: "Between plays or during quieter match moments, I want exceptional food options delivered fast and elegantly — whether personally selected or brought by autonomous services. Intelligent robotics, smart vending and refined alternatives make every meal feel elevated, frictionless and tailored to the VIP atmosphere.",
    },
    "vip-lounge": {
      subtitle: "A smooth, elegant transition into a premium environment",
      body: "When entering the private lounge, I want all cues — visuals, ambiance, personalized attention — to reinforce exclusivity and comfort. Hydration stations, curated food moments and intuitive displays help me settle in, explore amenities and enjoy a relaxing pre‑event atmosphere without ever feeling lost or unattended.",
    },
    "vip-networking": {
      subtitle: "A sophisticated social environment enhanced by seamless service",
      body: "During breaks, I want to meet, talk, enjoy curated refreshments and circulate freely without queuing or searching. Smart vending, catering services and instant digital touchpoints create a refined, fluid experience that supports both informal networking and high‑quality relaxation — all while maintaining the VIP standard.",
    },
  },
  "white-collar": {
    "commute": {
      subtitle: "Seamless, stress‑free commute to the workplace",
      body: "I want to plan my commute with confidence, knowing that parking, routes and last‑mile guidance are all taken care of. I need real‑time information and digital services that get me to the office on time, without traffic surprises or searching endlessly for a spot.",
    },
    "food-beverage-work": {
      subtitle: "Smart Payment, Personalized Dining & Loyalty Experience",
      body: "At lunchtime, I head to the cafeteria looking for my go-to healthy options without endless queues. I need to fuel up efficiently before afternoon calls, so I want a streamlined payment process that remembers my food preferences automatically without repeatedly inputting details.",
    },
    "welcome-area": {
      subtitle: "Frictionless arrival, check‑in and guest hospitality",
      body: "When I arrive on site, I want to pass security, find my way and welcome my guests without queues, confusion or awkward waiting. I need smart reception, clear signage and concierge‑like support so that every visit feels simple, professional and even a bit memorable and sustainable.",
    },
    "wellbeing-break": {
      subtitle: "Recharge, reset and take care of myself at work",
      body: "Between intense work blocks, I want easy ways to pause, move, breathe and look after my physical and mental health. I need simple access to healthy breaks, wellbeing activities and nudges that help me disconnect for a moment and come back focused and energized.",
    },
    "workplace": {
      subtitle: "Finding the right workspace, right now",
      body: "As my day fills up with meetings and focus time, I need to quickly see where my team is, find an available desk or room, and adapt to changing schedules. I want intuitive tools that show occupancy in real time, simplify bookings and keep my work environment comfortable and well‑serviced in the background.",
    },
  },
};
