/** Auto-generated by scripts/ingest_personae_journey_excel.py — do not edit by hand. */

export const PERSONA_JOURNEYS_EXCEL: Record<
  string,
  {
    image: string;
    moments: Array<{ id: string; label: string; left: number; top: number; w: number; h: number }>;
  }
> = {
  "blue-collar": {
    image: "/images/catalogue/assets/journeys/excel-maps/blue-collar.svg",
    moments: [
      { id: "blue-collar__commute", label: "Commute", left: 7.696, top: 32.028, w: 16.0, h: 10.0 },
      { id: "blue-collar__welcome-area", label: "Welcome Area", left: 20.845, top: 24.242, w: 16.0, h: 10.0 },
      { id: "blue-collar__workplace", label: "Workplace", left: 28.645, top: 60.653, w: 16.0, h: 10.0 },
      { id: "blue-collar__food-beverage-area", label: "Food & Beverage Area", left: 37.107, top: 58.295, w: 16.0, h: 10.0 },
      { id: "blue-collar__wellbeing-breaktime", label: "Wellbeing & breaktime", left: 53.447, top: 51.938, w: 16.0, h: 10.0 },
    ],
  },
  "client-heal": {
    image: "/images/catalogue/assets/journeys/excel-maps/client-heal.svg",
    moments: [
      { id: "client-heal__welcome-admission", label: "Welcome & Admission", left: 5.2, top: 30.453, w: 16.0, h: 10.0 },
      { id: "client-heal__kick-off-early-check", label: "Kick off & Early Check", left: 20.721, top: 23.057, w: 16.0, h: 10.0 },
      { id: "client-heal__internal-meetings-alignment", label: "Internal Meetings & Alignment", left: 31.847, top: 29.445, w: 16.0, h: 10.0 },
      { id: "client-heal__service-review-site-rounds", label: "Service Review & Site Rounds", left: 47.998, top: 51.523, w: 16.0, h: 10.0 },
      { id: "client-heal__lunch-stakeholder-engagement", label: "Lunch & Stakeholder Engagement", left: 59.45, top: 40.725, w: 16.0, h: 10.0 },
      { id: "client-heal__improvement-sessions-forward-planning", label: "Improvement Sessions & Forward Planning", left: 72.27, top: 72.909, w: 16.0, h: 10.0 },
    ],
  },
  "client-learn": {
    image: "/images/catalogue/assets/journeys/excel-maps/client-learn.svg",
    moments: [
      { id: "client-learn__welcome-admission", label: "Welcome & Admission", left: 5.2, top: 30.453, w: 16.0, h: 10.0 },
      { id: "client-learn__kick-off-and-early-check", label: "Kick-off and Early Check", left: 20.721, top: 23.057, w: 16.0, h: 10.0 },
      { id: "client-learn__internal-meetings-and-alignment", label: "Internal Meetings and Alignment", left: 31.847, top: 29.445, w: 16.0, h: 10.0 },
      { id: "client-learn__service-review-and-site-rounds", label: "Service Review and Site Rounds", left: 47.998, top: 51.523, w: 16.0, h: 10.0 },
      { id: "client-learn__lunch-stakeholders-engagement", label: "Lunch Stakeholders Engagement", left: 59.45, top: 40.725, w: 16.0, h: 10.0 },
      { id: "client-learn__improvement-session-forward-planning", label: "Improvement Session & Forward Planning", left: 72.27, top: 72.909, w: 16.0, h: 10.0 },
    ],
  },
  "client-play": {
    image: "/images/catalogue/assets/journeys/excel-maps/client-play.svg",
    moments: [
      { id: "client-play__welcome-admission", label: "Welcome & Admission", left: 5.2, top: 30.453, w: 16.0, h: 10.0 },
      { id: "client-play__kick-off-and-early-check", label: "Kick-off and Early Check", left: 20.721, top: 23.057, w: 16.0, h: 10.0 },
      { id: "client-play__internal-meetings-and-alignment", label: "Internal Meetings and Alignment", left: 31.847, top: 29.445, w: 16.0, h: 10.0 },
      { id: "client-play__service-review-and-site-rounds", label: "Service Review and Site Rounds", left: 47.998, top: 51.523, w: 16.0, h: 10.0 },
      { id: "client-play__lunch-stakeholders-engagement", label: "Lunch Stakeholders Engagement", left: 59.45, top: 40.725, w: 16.0, h: 10.0 },
      { id: "client-play__improvement-session-forward-planning", label: "Improvement Session & Forward Planning", left: 72.27, top: 72.909, w: 16.0, h: 10.0 },
    ],
  },
  "client-work": {
    image: "/images/catalogue/assets/journeys/excel-maps/client-work.svg",
    moments: [
      { id: "client-work__welcome-admission", label: "Welcome & Admission", left: 5.2, top: 30.453, w: 16.0, h: 10.0 },
      { id: "client-work__kick-off-early-check", label: "Kick off & Early Check", left: 20.721, top: 23.057, w: 16.0, h: 10.0 },
      { id: "client-work__internal-meetings-alignment", label: "Internal Meetings & Alignment", left: 31.847, top: 29.445, w: 16.0, h: 10.0 },
      { id: "client-work__service-review-site-rounds", label: "Service Review & Site Rounds", left: 47.998, top: 51.523, w: 16.0, h: 10.0 },
      { id: "client-work__lunch-stakeholder-engagement", label: "Lunch & Stakeholder Engagement", left: 59.45, top: 40.725, w: 16.0, h: 10.0 },
      { id: "client-work__improvement-sessions-forward-planning", label: "Improvement Sessions & Forward Planning", left: 72.27, top: 72.909, w: 16.0, h: 10.0 },
    ],
  },
  "doctor": {
    image: "/images/catalogue/assets/journeys/excel-maps/doctor.svg",
    moments: [
      { id: "doctor__commute", label: "Commute", left: 9.759, top: 22.371, w: 16.0, h: 10.0 },
      { id: "doctor__patient-consultations", label: "Patient Consultations", left: 20.192, top: 15.83, w: 16.0, h: 10.0 },
      { id: "doctor__team-meetings", label: "Team Meetings", left: 31.286, top: 22.218, w: 16.0, h: 10.0 },
      { id: "doctor__food-beverage-area", label: "Food & Beverage Area", left: 65.062, top: 18.928, w: 16.0, h: 10.0 },
      { id: "doctor__breaktime", label: "Breaktime", left: 56.41, top: 46.186, w: 16.0, h: 10.0 },
      { id: "doctor__afternoon-rounds", label: "Afternoon Rounds", left: 44.455, top: 53.683, w: 16.0, h: 10.0 },
      { id: "doctor__end-of-shift", label: "End of Shift", left: 82.888, top: 56.852, w: 16.0, h: 10.0 },
    ],
  },
  "grey-collar": {
    image: "/images/catalogue/assets/journeys/excel-maps/grey-collar.svg",
    moments: [
      { id: "grey-collar__commute", label: "Commute", left: 5.303, top: 28.665, w: 16.0, h: 10.0 },
      { id: "grey-collar__welcome-area", label: "Welcome Area", left: 35.023, top: 34.353, w: 16.0, h: 10.0 },
      { id: "grey-collar__workplace", label: "Workplace", left: 44.221, top: 54.633, w: 16.0, h: 10.0 },
      { id: "grey-collar__food-beverage-area", label: "Food & Beverage Area", left: 22.52, top: 59.497, w: 16.0, h: 10.0 },
      { id: "grey-collar__wellbeing-breaktime", label: "Wellbeing & Breaktime", left: 14.601, top: 61.869, w: 16.0, h: 10.0 },
    ],
  },
  "military": {
    image: "/images/catalogue/assets/journeys/excel-maps/military.svg",
    moments: [
      { id: "military__morning-routine", label: "Morning Routine", left: 7.051, top: 66.655, w: 16.0, h: 10.0 },
      { id: "military__work-activities", label: "Work/Activities", left: 16.822, top: 75.93, w: 16.0, h: 10.0 },
      { id: "military__lunch-break", label: "Lunch Break", left: 24.34, top: 43.125, w: 16.0, h: 10.0 },
      { id: "military__afterwork", label: "Afterwork", left: 51.257, top: 67.613, w: 16.0, h: 10.0 },
      { id: "military__dinner-with-regiment", label: "Dinner with Regiment", left: 69.675, top: 68.119, w: 16.0, h: 10.0 },
      { id: "military__evening-routine", label: "Evening Routine", left: 61.578, top: 19.386, w: 16.0, h: 10.0 },
    ],
  },
  "nurse": {
    image: "/images/catalogue/assets/journeys/excel-maps/nurse.svg",
    moments: [
      { id: "nurse__commute", label: "Commute", left: 12.401, top: 26.725, w: 16.0, h: 10.0 },
      { id: "nurse__welcome", label: "Welcome", left: 22.825, top: 20.176, w: 16.0, h: 10.0 },
      { id: "nurse__nursing-care", label: "Nursing Care", left: 33.926, top: 26.564, w: 16.0, h: 10.0 },
      { id: "nurse__food-beverage-area", label: "Food & Beverage Area", left: 52.93, top: 29.847, w: 16.0, h: 10.0 },
      { id: "nurse__breaktime", label: "Breaktime", left: 60.481, top: 20.699, w: 16.0, h: 10.0 },
      { id: "nurse__freetime-work-life-balance", label: "Freetime & Work/Life Balance", left: 44.09, top: 68.943, w: 16.0, h: 10.0 },
    ],
  },
  "operator-heal": {
    image: "/images/catalogue/assets/journeys/excel-maps/operator-heal.svg",
    moments: [
      { id: "operator-heal__kick-off-early-check", label: "Kick-off & Early Check", left: 5.2, top: 30.453, w: 16.0, h: 10.0 },
      { id: "operator-heal__kitchen-back-kitchen-fm-checking-round", label: "Kitchen / Back Kitchen: FM Checking Round", left: 20.721, top: 23.057, w: 16.0, h: 10.0 },
      { id: "operator-heal__office-time", label: "Office Time", left: 31.847, top: 29.445, w: 16.0, h: 10.0 },
      { id: "operator-heal__food-beverage-area", label: "Food & Beverage Area", left: 47.998, top: 51.523, w: 16.0, h: 10.0 },
      { id: "operator-heal__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 56.364, top: 81.672, w: 16.0, h: 10.0 },
    ],
  },
  "operator-learn": {
    image: "/images/catalogue/assets/journeys/excel-maps/operator-learn.svg",
    moments: [
      { id: "operator-learn__kick-off-early-check", label: "Kick-off & Early Check", left: 5.2, top: 30.453, w: 16.0, h: 10.0 },
      { id: "operator-learn__kitchen-back-kitchen-fm-checking-round", label: "Kitchen/Back Kitchen: FM Checking Round", left: 20.721, top: 23.057, w: 16.0, h: 10.0 },
      { id: "operator-learn__office-time", label: "Office Time", left: 31.847, top: 29.445, w: 16.0, h: 10.0 },
      { id: "operator-learn__food-beverage-area", label: "Food & Beverage Area", left: 47.998, top: 51.523, w: 16.0, h: 10.0 },
      { id: "operator-learn__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 56.364, top: 81.672, w: 16.0, h: 10.0 },
    ],
  },
  "operator-play": {
    image: "/images/catalogue/assets/journeys/excel-maps/operator-play.svg",
    moments: [
      { id: "operator-play__kick-off-early-check", label: "Kick-off & Early Check", left: 5.2, top: 30.453, w: 16.0, h: 10.0 },
      { id: "operator-play__kitchen-back-kitchen-fm-checking-round", label: "Kitchen/Back Kitchen: FM Checking Round", left: 20.721, top: 23.057, w: 16.0, h: 10.0 },
      { id: "operator-play__office-time", label: "Office Time", left: 31.847, top: 29.445, w: 16.0, h: 10.0 },
      { id: "operator-play__food-beverage-area", label: "Food & Beverage Area", left: 47.998, top: 51.523, w: 16.0, h: 10.0 },
      { id: "operator-play__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 56.364, top: 81.672, w: 16.0, h: 10.0 },
    ],
  },
  "operator-work": {
    image: "/images/catalogue/assets/journeys/excel-maps/operator-work.svg",
    moments: [
      { id: "operator-work__kick-off-early-check", label: "Kick-off & Early Check", left: 5.2, top: 30.453, w: 16.0, h: 10.0 },
      { id: "operator-work__kitchen-back-kitchen-fm-checking-round", label: "Kitchen / Back Kitchen: FM Checking Round", left: 20.721, top: 23.057, w: 16.0, h: 10.0 },
      { id: "operator-work__office-time", label: "Office Time", left: 31.847, top: 29.445, w: 16.0, h: 10.0 },
      { id: "operator-work__food-beverage-area", label: "Food & Beverage Area", left: 47.998, top: 51.523, w: 16.0, h: 10.0 },
      { id: "operator-work__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 56.364, top: 81.672, w: 16.0, h: 10.0 },
    ],
  },
  "parent": {
    image: "/images/catalogue/assets/journeys/excel-maps/parent.svg",
    moments: [
      { id: "parent__prep-commute", label: "Prep & Commute", left: 10.738, top: 69.422, w: 16.0, h: 10.0 },
      { id: "parent__during-school-day", label: "During School Day", left: 23.825, top: 65.985, w: 16.0, h: 10.0 },
      { id: "parent__meal-visibility", label: "Meal Visibility", left: 31.376, top: 35.654, w: 16.0, h: 10.0 },
      { id: "parent__pick-up-time", label: "Pick-up Time", left: 39.345, top: 33.843, w: 16.0, h: 10.0 },
      { id: "parent__evening-routine", label: "Evening Routine", left: 50.692, top: 22.092, w: 16.0, h: 10.0 },
      { id: "parent__weekly-preparation", label: "Weekly Preparation", left: 59.951, top: 62.434, w: 16.0, h: 10.0 },
    ],
  },
  "participant": {
    image: "/images/catalogue/assets/journeys/excel-maps/participant.svg",
    moments: [
      { id: "participant__commute", label: "Commute", left: 6.494, top: 38.044, w: 16.0, h: 10.0 },
      { id: "participant__arrival-access", label: "Arrival & Access", left: 22.048, top: 30.657, w: 16.0, h: 10.0 },
      { id: "participant__navigating-the-show", label: "Navigating the Show", left: 33.142, top: 37.03, w: 16.0, h: 10.0 },
      { id: "participant__attending-a-talk-or-demo", label: "Attending a Talk or Demo", left: 45.453, top: 26.848, w: 16.0, h: 10.0 },
      { id: "participant__networking-breaktime", label: "Networking & Breaktime", left: 63.382, top: 29.6, w: 16.0, h: 10.0 },
      { id: "participant__after-event", label: "After Event", left: 53.488, top: 59.464, w: 16.0, h: 10.0 },
    ],
  },
  "patient": {
    image: "/images/catalogue/assets/journeys/excel-maps/patient.svg",
    moments: [
      { id: "patient__commute", label: "Commute", left: 11.8, top: 27.72, w: 16.0, h: 10.0 },
      { id: "patient__welcome-and-admission", label: "Welcome and Admission", left: 16.611, top: 30.493, w: 16.0, h: 10.0 },
      { id: "patient__care-and-daily-routine", label: "Care and Daily Routine", left: 22.08, top: 24.299, w: 16.0, h: 10.0 },
      { id: "patient__snack", label: "Snack", left: 29.649, top: 28.562, w: 16.0, h: 10.0 },
      { id: "patient__lunch-break", label: "Lunch Break", left: 40.502, top: 56.212, w: 16.0, h: 10.0 },
      { id: "patient__leaving-the-hospital", label: "Leaving the Hospital", left: 51.555, top: 54.301, w: 16.0, h: 10.0 },
      { id: "patient__rest-personal-balance", label: "Rest & Personal Balance", left: 68.911, top: 19.62, w: 16.0, h: 10.0 },
    ],
  },
  "schoolchild": {
    image: "/images/catalogue/assets/journeys/excel-maps/schoolchild.svg",
    moments: [
      { id: "schoolchild__commute", label: "Commute", left: 3.284, top: 33.759, w: 16.0, h: 10.0 },
      { id: "schoolchild__welcome-at-school", label: "Welcome at School", left: 14.945, top: 27.071, w: 16.0, h: 10.0 },
      { id: "schoolchild__in-class", label: "In Class", left: 25.812, top: 39.199, w: 16.0, h: 10.0 },
      { id: "schoolchild__food-beverage-area", label: "Food & Beverage Area", left: 49.506, top: 43.417, w: 16.0, h: 10.0 },
      { id: "schoolchild__freetime", label: "Freetime", left: 58.869, top: 45.12, w: 16.0, h: 10.0 },
    ],
  },
  "senior": {
    image: "/images/catalogue/assets/journeys/excel-maps/senior.svg",
    moments: [
      { id: "senior__welcome-residents", label: "Welcome Residents", left: 26.484, top: 48.926, w: 16.0, h: 10.0 },
      { id: "senior__breakfast", label: "Breakfast", left: 34.947, top: 46.537, w: 16.0, h: 10.0 },
      { id: "senior__activities", label: "Activities", left: 43.829, top: 34.376, w: 16.0, h: 10.0 },
      { id: "senior__lunch-break", label: "Lunch Break", left: 62.242, top: 47.658, w: 16.0, h: 10.0 },
      { id: "senior__breaktime", label: "Breaktime", left: 78.628, top: 68.182, w: 16.0, h: 10.0 },
      { id: "senior__dinner", label: "Dinner", left: 70.317, top: 17.463, w: 16.0, h: 10.0 },
    ],
  },
  "sport-fan": {
    image: "/images/catalogue/assets/journeys/excel-maps/sport-fan.svg",
    moments: [
      { id: "sport-fan__commute", label: "Commute", left: 7.414, top: 37.955, w: 16.0, h: 10.0 },
      { id: "sport-fan__welcome-area", label: "Welcome Area", left: 22.973, top: 30.571, w: 16.0, h: 10.0 },
      { id: "sport-fan__waiting-for-the-game", label: "Waiting for the Game", left: 34.061, top: 36.929, w: 16.0, h: 10.0 },
      { id: "sport-fan__social-time-match-time", label: "Social Time / Match Time", left: 52.026, top: 41.637, w: 16.0, h: 10.0 },
      { id: "sport-fan__halftime-activities", label: "Halftime Activities", left: 59.627, top: 48.109, w: 16.0, h: 10.0 },
      { id: "sport-fan__after-event", label: "After Event", left: 44.045, top: 66.619, w: 16.0, h: 10.0 },
    ],
  },
  "student": {
    image: "/images/catalogue/assets/journeys/excel-maps/student.svg",
    moments: [
      { id: "student__commute", label: "Commute", left: 10.285, top: 38.417, w: 16.0, h: 10.0 },
      { id: "student__welcome-area", label: "Welcome Area", left: 25.585, top: 46.167, w: 16.0, h: 10.0 },
      { id: "student__studies", label: "Studies", left: 36.941, top: 37.416, w: 16.0, h: 10.0 },
      { id: "student__food-beverage-area", label: "Food & Beverage Area", left: 65.691, top: 69.687, w: 16.0, h: 10.0 },
      { id: "student__freetime-studies-life-balance", label: "Freetime & Studies/Life Balance", left: 50.889, top: 82.728, w: 16.0, h: 10.0 },
    ],
  },
  "teacher": {
    image: "/images/catalogue/assets/journeys/excel-maps/teacher.svg",
    moments: [
      { id: "teacher__commute", label: "Commute", left: 3.284, top: 33.759, w: 16.0, h: 10.0 },
      { id: "teacher__arrival-to-the-school-campus", label: "Arrival to the School / Campus", left: 14.944, top: 27.07, w: 16.0, h: 10.0 },
      { id: "teacher__teaching", label: "Teaching", left: 25.812, top: 39.199, w: 16.0, h: 10.0 },
      { id: "teacher__food-beverage-area", label: "Food & Beverage Area", left: 44.772, top: 63.409, w: 16.0, h: 10.0 },
      { id: "teacher__freetime-work-life-balance", label: "Freetime & Work/Life Balance", left: 36.281, top: 76.521, w: 16.0, h: 10.0 },
    ],
  },
  "tourist": {
    image: "/images/catalogue/assets/journeys/excel-maps/tourist.svg",
    moments: [
      { id: "tourist__prep-commute", label: "Prep & Commute", left: 4.112, top: 42.461, w: 16.0, h: 10.0 },
      { id: "tourist__arrival-access", label: "Arrival & Access", left: 19.722, top: 35.085, w: 16.0, h: 10.0 },
      { id: "tourist__eat-drink", label: "Eat & Drink", left: 30.821, top: 41.463, w: 16.0, h: 10.0 },
      { id: "tourist__social-time-work", label: "Social time/Work", left: 42.37, top: 64.277, w: 16.0, h: 10.0 },
      { id: "tourist__fast-access-to-gate", label: "Fast Access to Gate", left: 51.12, top: 59.904, w: 16.0, h: 10.0 },
    ],
  },
  "vip-guest": {
    image: "/images/catalogue/assets/journeys/excel-maps/vip-guest.svg",
    moments: [
      { id: "vip-guest__prep-commute", label: "Prep & Commute", left: 25.585, top: 46.167, w: 16.0, h: 10.0 },
      { id: "vip-guest__arrival-access", label: "Arrival & Access", left: 30.763, top: 45.387, w: 16.0, h: 10.0 },
      { id: "vip-guest__private-lounge-entry", label: "Private Lounge Entry", left: 59.75, top: 50.547, w: 16.0, h: 10.0 },
      { id: "vip-guest__networking-event-time", label: "Networking & Event Time", left: 69.149, top: 40.594, w: 16.0, h: 10.0 },
      { id: "vip-guest__eat-drink", label: "Eat & Drink", left: 53.021, top: 74.284, w: 16.0, h: 10.0 },
      { id: "vip-guest__after-event", label: "After Event", left: 48.124, top: 77.808, w: 16.0, h: 10.0 },
    ],
  },
  "white-collar": {
    image: "/images/catalogue/assets/journeys/excel-maps/white-collar.svg",
    moments: [
      { id: "white-collar__commute", label: "Commute", left: 4.729, top: 28.69, w: 16.0, h: 10.0 },
      { id: "white-collar__welcome-area", label: "Welcome Area", left: 21.172, top: 30.998, w: 16.0, h: 10.0 },
      { id: "white-collar__workplace", label: "Workplace", left: 29.3, top: 76.513, w: 16.0, h: 10.0 },
      { id: "white-collar__food-beverage-area", label: "Food & Beverage Area", left: 37.979, top: 79.218, w: 16.0, h: 10.0 },
      { id: "white-collar__wellbeing-breaktime", label: "Wellbeing & Breaktime", left: 13.165, top: 78.883, w: 16.0, h: 10.0 },
    ],
  },
};
