/** Auto-generated by scripts/ingest_personae_journey_excel.py — do not edit by hand. */

export const PERSONA_JOURNEYS_EXCEL: Record<
  string,
  {
    image: string;
    moments: Array<{ id: string; label: string; left: number; top: number; w: number; h: number }>;
  }
> = {
  "blue-collar": {
    image: "/images/catalogue/assets/journeys/excel-maps/blue-collar.png",
    moments: [
      { id: "blue-collar__commute", label: "Commute", left: 4.934, top: 29.37, w: 16.0, h: 10.0 },
      { id: "blue-collar__welcome-area", label: "Welcome Area", left: 26.212, top: 34.585, w: 16.0, h: 10.0 },
      { id: "blue-collar__workplace", label: "Workplace", left: 45.005, top: 27.027, w: 16.0, h: 10.0 },
      { id: "blue-collar__food-beverage-area", label: "Food & Beverage Area", left: 37.087, top: 16.496, w: 16.0, h: 10.0 },
      { id: "blue-collar__wellbeing-breaktime", label: "Wellbeing & breaktime", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "client-heal": {
    image: "/images/catalogue/assets/journeys/excel-maps/client-heal.png",
    moments: [
      { id: "client-heal__welcome-admission", label: "Welcome & Admission", left: 7.625, top: 19.798, w: 16.0, h: 10.0 },
      { id: "client-heal__kick-off-early-check", label: "Kick off & Early Check", left: 32.412, top: 36.937, w: 16.0, h: 10.0 },
      { id: "client-heal__internal-meetings-alignment", label: "Internal Meetings & Alignment", left: 23.549, top: 51.442, w: 16.0, h: 10.0 },
      { id: "client-heal__service-review-site-rounds", label: "Service Review & Site Rounds", left: 43.17, top: 77.648, w: 16.0, h: 10.0 },
      { id: "client-heal__lunch-stakeholder-engagement", label: "Lunch & Stakeholder Engagement", left: 50.915, top: 76.744, w: 16.0, h: 10.0 },
      { id: "client-heal__improvement-sessions-forward-planning", label: "Improvement Sessions & Forward Planning", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "client-learn": {
    image: "/images/catalogue/assets/journeys/excel-maps/client-learn.png",
    moments: [
      { id: "client-learn__welcome-admission", label: "Welcome & Admission", left: 7.625, top: 19.798, w: 16.0, h: 10.0 },
      { id: "client-learn__kick-off-and-early-check", label: "Kick-off and Early Check", left: 32.412, top: 36.937, w: 16.0, h: 10.0 },
      { id: "client-learn__internal-meetings-and-alignment", label: "Internal Meetings and Alignment", left: 23.549, top: 51.442, w: 16.0, h: 10.0 },
      { id: "client-learn__service-review-and-site-rounds", label: "Service Review and Site Rounds", left: 43.17, top: 77.648, w: 16.0, h: 10.0 },
      { id: "client-learn__lunch-stakeholders-engagement", label: "Lunch Stakeholders Engagement", left: 50.915, top: 76.744, w: 16.0, h: 10.0 },
      { id: "client-learn__improvement-session-forward-planning", label: "Improvement Session & Forward Planning", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "client-play": {
    image: "/images/catalogue/assets/journeys/excel-maps/client-play.png",
    moments: [
      { id: "client-play__welcome-admission", label: "Welcome & Admission", left: 7.625, top: 19.798, w: 16.0, h: 10.0 },
      { id: "client-play__kick-off-and-early-check", label: "Kick-off and Early Check", left: 32.412, top: 36.937, w: 16.0, h: 10.0 },
      { id: "client-play__internal-meetings-and-alignment", label: "Internal Meetings and Alignment", left: 23.549, top: 51.442, w: 16.0, h: 10.0 },
      { id: "client-play__service-review-and-site-rounds", label: "Service Review and Site Rounds", left: 43.17, top: 77.648, w: 16.0, h: 10.0 },
      { id: "client-play__lunch-stakeholders-engagement", label: "Lunch Stakeholders Engagement", left: 50.915, top: 76.744, w: 16.0, h: 10.0 },
      { id: "client-play__improvement-session-forward-planning", label: "Improvement Session & Forward Planning", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "client-work": {
    image: "/images/catalogue/assets/journeys/excel-maps/client-work.png",
    moments: [
      { id: "client-work__welcome-admission", label: "Welcome & Admission", left: 7.625, top: 19.798, w: 16.0, h: 10.0 },
      { id: "client-work__kick-off-early-check", label: "Kick off & Early Check", left: 32.412, top: 36.937, w: 16.0, h: 10.0 },
      { id: "client-work__internal-meetings-alignment", label: "Internal Meetings & Alignment", left: 23.549, top: 51.442, w: 16.0, h: 10.0 },
      { id: "client-work__service-review-site-rounds", label: "Service Review & Site Rounds", left: 43.17, top: 77.648, w: 16.0, h: 10.0 },
      { id: "client-work__lunch-stakeholder-engagement", label: "Lunch & Stakeholder Engagement", left: 50.915, top: 76.744, w: 16.0, h: 10.0 },
      { id: "client-work__improvement-sessions-forward-planning", label: "Improvement Sessions & Forward Planning", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "doctor": {
    image: "/images/catalogue/assets/journeys/excel-maps/doctor.png",
    moments: [
      { id: "doctor__commute", label: "Commute", left: 4.969, top: 21.889, w: 16.0, h: 10.0 },
      { id: "doctor__patient-consultations", label: "Patient Consultations", left: 22.635, top: 29.005, w: 16.0, h: 10.0 },
      { id: "doctor__team-meetings", label: "Team Meetings", left: 31.017, top: 32.874, w: 16.0, h: 10.0 },
      { id: "doctor__food-beverage-area", label: "Food & Beverage Area", left: 50.018, top: 57.676, w: 16.0, h: 10.0 },
      { id: "doctor__breaktime", label: "Breaktime", left: 39.821, top: 68.541, w: 16.0, h: 10.0 },
      { id: "doctor__afternoon-rounds", label: "Afternoon Rounds", left: 59.298, top: 82.624, w: 16.0, h: 10.0 },
      { id: "doctor__end-of-shift", label: "End of Shift", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "grey-collar": {
    image: "/images/catalogue/assets/journeys/excel-maps/grey-collar.png",
    moments: [
      { id: "grey-collar__commute", label: "Commute", left: 12.988, top: 30.692, w: 16.0, h: 10.0 },
      { id: "grey-collar__welcome-area", label: "Welcome Area", left: 31.151, top: 38.005, w: 16.0, h: 10.0 },
      { id: "grey-collar__workplace", label: "Workplace", left: 21.855, top: 60.283, w: 16.0, h: 10.0 },
      { id: "grey-collar__food-beverage-area", label: "Food & Beverage Area", left: 5.366, top: 63.412, w: 16.0, h: 10.0 },
      { id: "grey-collar__wellbeing-breaktime", label: "Wellbeing & Breaktime", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "military": {
    image: "/images/catalogue/assets/journeys/excel-maps/military.png",
    moments: [
      { id: "military__morning-routine", label: "Morning Routine", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
      { id: "military__work-activities", label: "Work/Activities", left: 5.444, top: 68.201, w: 16.0, h: 10.0 },
      { id: "military__lunch-break", label: "Lunch Break", left: 13.675, top: 59.855, w: 16.0, h: 10.0 },
      { id: "military__afterwork", label: "Afterwork", left: 29.455, top: 63.37, w: 16.0, h: 10.0 },
      { id: "military__dinner-with-regiment", label: "Dinner with Regiment", left: 38.6, top: 64.758, w: 16.0, h: 10.0 },
      { id: "military__evening-routine", label: "Evening Routine", left: 21.369, top: 40.302, w: 16.0, h: 10.0 },
    ],
  },
  "nurse": {
    image: "/images/catalogue/assets/journeys/excel-maps/nurse.png",
    moments: [
      { id: "nurse__commute", label: "Commute", left: 5.515, top: 24.759, w: 16.0, h: 10.0 },
      { id: "nurse__welcome", label: "Welcome", left: 45.684, top: 48.244, w: 16.0, h: 10.0 },
      { id: "nurse__nursing-care", label: "Nursing Care", left: 54.463, top: 52.59, w: 16.0, h: 10.0 },
      { id: "nurse__food-beverage-area", label: "Food & Beverage Area", left: 29.617, top: 72.687, w: 16.0, h: 10.0 },
      { id: "nurse__breaktime", label: "Breaktime", left: 21.538, top: 68.752, w: 16.0, h: 10.0 },
      { id: "nurse__freetime-work-life-balance", label: "Freetime & Work/Life Balance", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "operator-heal": {
    image: "/images/catalogue/assets/journeys/excel-maps/operator-heal.png",
    moments: [
      { id: "operator-heal__kick-off-early-check", label: "Kick-off & Early Check", left: 7.625, top: 19.798, w: 16.0, h: 10.0 },
      { id: "operator-heal__kitchen-back-kitchen-fm-checking-round", label: "Kitchen / Back Kitchen: FM Checking Round", left: 23.549, top: 51.442, w: 16.0, h: 10.0 },
      { id: "operator-heal__office-time", label: "Office Time", left: 60.578, top: 62.611, w: 16.0, h: 10.0 },
      { id: "operator-heal__food-beverage-area", label: "Food & Beverage Area", left: 31.734, top: 89.589, w: 16.0, h: 10.0 },
      { id: "operator-heal__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "operator-learn": {
    image: "/images/catalogue/assets/journeys/excel-maps/operator-learn.png",
    moments: [
      { id: "operator-learn__kick-off-early-check", label: "Kick-off & Early Check", left: 7.625, top: 19.798, w: 16.0, h: 10.0 },
      { id: "operator-learn__kitchen-back-kitchen-fm-checking-round", label: "Kitchen/Back Kitchen: FM Checking Round", left: 23.549, top: 51.442, w: 16.0, h: 10.0 },
      { id: "operator-learn__office-time", label: "Office Time", left: 60.578, top: 62.611, w: 16.0, h: 10.0 },
      { id: "operator-learn__food-beverage-area", label: "Food & Beverage Area", left: 31.734, top: 89.589, w: 16.0, h: 10.0 },
      { id: "operator-learn__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "operator-play": {
    image: "/images/catalogue/assets/journeys/excel-maps/operator-play.png",
    moments: [
      { id: "operator-play__kick-off-early-check", label: "Kick-off & Early Check", left: 7.625, top: 19.798, w: 16.0, h: 10.0 },
      { id: "operator-play__kitchen-back-kitchen-fm-checking-round", label: "Kitchen/Back Kitchen: FM Checking Round", left: 23.549, top: 51.442, w: 16.0, h: 10.0 },
      { id: "operator-play__office-time", label: "Office Time", left: 60.578, top: 62.611, w: 16.0, h: 10.0 },
      { id: "operator-play__food-beverage-area", label: "Food & Beverage Area", left: 31.733, top: 89.59, w: 16.0, h: 10.0 },
      { id: "operator-play__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "operator-work": {
    image: "/images/catalogue/assets/journeys/excel-maps/operator-work.png",
    moments: [
      { id: "operator-work__kick-off-early-check", label: "Kick-off & Early Check", left: 7.625, top: 19.798, w: 16.0, h: 10.0 },
      { id: "operator-work__kitchen-back-kitchen-fm-checking-round", label: "Kitchen / Back Kitchen: FM Checking Round", left: 23.549, top: 51.442, w: 16.0, h: 10.0 },
      { id: "operator-work__office-time", label: "Office Time", left: 60.578, top: 62.611, w: 16.0, h: 10.0 },
      { id: "operator-work__food-beverage-area", label: "Food & Beverage Area", left: 31.734, top: 89.589, w: 16.0, h: 10.0 },
      { id: "operator-work__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "parent": {
    image: "/images/catalogue/assets/journeys/excel-maps/parent.png",
    moments: [
      { id: "parent__prep-commute", label: "Prep & Commute", left: 4.907, top: 58.219, w: 16.0, h: 10.0 },
      { id: "parent__during-school-day", label: "During School Day", left: 15.34, top: 33.242, w: 16.0, h: 10.0 },
      { id: "parent__meal-visibility", label: "Meal Visibility", left: 24.366, top: 22.53, w: 16.0, h: 10.0 },
      { id: "parent__pick-up-time", label: "Pick-up Time", left: 39.525, top: 18.729, w: 16.0, h: 10.0 },
      { id: "parent__evening-routine", label: "Evening Routine", left: 31.981, top: 66.598, w: 16.0, h: 10.0 },
      { id: "parent__weekly-preparation", label: "Weekly Preparation", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "participant": {
    image: "/images/catalogue/assets/journeys/excel-maps/participant.png",
    moments: [
      { id: "participant__commute", label: "Commute", left: 8.354, top: 27.39, w: 16.0, h: 10.0 },
      { id: "participant__arrival-access", label: "Arrival & Access", left: 33.664, top: 28.441, w: 16.0, h: 10.0 },
      { id: "participant__navigating-the-show", label: "Navigating the Show", left: 49.429, top: 22.233, w: 16.0, h: 10.0 },
      { id: "participant__attending-a-talk-or-demo", label: "Attending a Talk or Demo", left: 61.239, top: 55.487, w: 16.0, h: 10.0 },
      { id: "participant__networking-breaktime", label: "Networking & Breaktime", left: 19.564, top: 83.031, w: 16.0, h: 10.0 },
      { id: "participant__after-event", label: "After Event", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "patient": {
    image: "/images/catalogue/assets/journeys/excel-maps/patient.png",
    moments: [
      { id: "patient__commute", label: "Commute", left: 5.177, top: 25.754, w: 16.0, h: 10.0 },
      { id: "patient__welcome-and-admission", label: "Welcome and Admission", left: 30.982, top: 37.986, w: 16.0, h: 10.0 },
      { id: "patient__care-and-daily-routine", label: "Care and Daily Routine", left: 18.27, top: 53.949, w: 16.0, h: 10.0 },
      { id: "patient__snack", label: "Snack", left: 48.788, top: 61.664, w: 16.0, h: 10.0 },
      { id: "patient__lunch-break", label: "Lunch Break", left: 70.955, top: 57.536, w: 16.0, h: 10.0 },
      { id: "patient__leaving-the-hospital", label: "Leaving the Hospital", left: 79.878, top: 22.714, w: 16.0, h: 10.0 },
      { id: "patient__rest-personal-balance", label: "Rest & Personal Balance", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "schoolchild": {
    image: "/images/catalogue/assets/journeys/excel-maps/schoolchild.png",
    moments: [
      { id: "schoolchild__commute", label: "Commute", left: 5.577, top: 41.8, w: 16.0, h: 10.0 },
      { id: "schoolchild__welcome-at-school", label: "Welcome at School", left: 27.618, top: 39.414, w: 16.0, h: 10.0 },
      { id: "schoolchild__in-class", label: "In Class", left: 35.801, top: 64.339, w: 16.0, h: 10.0 },
      { id: "schoolchild__food-beverage-area", label: "Food & Beverage Area", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
      { id: "schoolchild__freetime", label: "Freetime", left: 43.543, top: 16.355, w: 16.0, h: 10.0 },
    ],
  },
  "senior": {
    image: "/images/catalogue/assets/journeys/excel-maps/senior.png",
    moments: [
      { id: "senior__welcome-residents", label: "Welcome Residents", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
      { id: "senior__breakfast", label: "Breakfast", left: 11.147, top: 50.45, w: 16.0, h: 10.0 },
      { id: "senior__activities", label: "Activities", left: 38.038, top: 48.722, w: 16.0, h: 10.0 },
      { id: "senior__lunch-break", label: "Lunch Break", left: 46.17, top: 26.24, w: 16.0, h: 10.0 },
      { id: "senior__breaktime", label: "Breaktime", left: 30.529, top: 24.213, w: 16.0, h: 10.0 },
      { id: "senior__dinner", label: "Dinner", left: 72.296, top: 34.09, w: 16.0, h: 10.0 },
    ],
  },
  "sport-fan": {
    image: "/images/catalogue/assets/journeys/excel-maps/sport-fan.png",
    moments: [
      { id: "sport-fan__commute", label: "Commute", left: 4.778, top: 35.296, w: 16.0, h: 10.0 },
      { id: "sport-fan__welcome-area", label: "Welcome Area", left: 13.248, top: 36.896, w: 16.0, h: 10.0 },
      { id: "sport-fan__waiting-for-the-game", label: "Waiting for the Game", left: 32.007, top: 34.309, w: 16.0, h: 10.0 },
      { id: "sport-fan__social-time-match-time", label: "Social Time / Match Time", left: 45.002, top: 17.604, w: 16.0, h: 10.0 },
      { id: "sport-fan__halftime-activities", label: "Halftime Activities", left: 21.897, top: 69.286, w: 16.0, h: 10.0 },
      { id: "sport-fan__after-event", label: "After Event", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "student": {
    image: "/images/catalogue/assets/journeys/excel-maps/student.png",
    moments: [
      { id: "student__commute", label: "Commute", left: 6.098, top: 31.892, w: 16.0, h: 10.0 },
      { id: "student__welcome-area", label: "Welcome Area", left: 14.863, top: 37.359, w: 16.0, h: 10.0 },
      { id: "student__studies", label: "Studies", left: 33.453, top: 69.693, w: 16.0, h: 10.0 },
      { id: "student__food-beverage-area", label: "Food & Beverage Area", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
      { id: "student__freetime-studies-life-balance", label: "Freetime & Studies/Life Balance", left: 48.486, top: 16.822, w: 16.0, h: 10.0 },
    ],
  },
  "teacher": {
    image: "/images/catalogue/assets/journeys/excel-maps/teacher.png",
    moments: [
      { id: "teacher__commute", label: "Commute", left: 5.577, top: 41.8, w: 16.0, h: 10.0 },
      { id: "teacher__arrival-to-the-school-campus", label: "Arrival to the School / Campus", left: 30.251, top: 45.608, w: 16.0, h: 10.0 },
      { id: "teacher__teaching", label: "Teaching", left: 20.499, top: 71.332, w: 16.0, h: 10.0 },
      { id: "teacher__food-beverage-area", label: "Food & Beverage Area", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
      { id: "teacher__freetime-work-life-balance", label: "Freetime & Work/Life Balance", left: 39.637, top: 16.077, w: 16.0, h: 10.0 },
    ],
  },
  "tourist": {
    image: "/images/catalogue/assets/journeys/excel-maps/tourist.png",
    moments: [
      { id: "tourist__prep-commute", label: "Prep & Commute", left: 4.722, top: 28.765, w: 16.0, h: 10.0 },
      { id: "tourist__arrival-access", label: "Arrival & Access", left: 32.747, top: 39.199, w: 16.0, h: 10.0 },
      { id: "tourist__eat-drink", label: "Eat & Drink", left: 25.216, top: 70.862, w: 16.0, h: 10.0 },
      { id: "tourist__social-time-work", label: "Social time/Work", left: 16.482, top: 75.589, w: 16.0, h: 10.0 },
      { id: "tourist__fast-access-to-gate", label: "Fast Access to Gate", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
    ],
  },
  "vip-guest": {
    image: "/images/catalogue/assets/journeys/excel-maps/vip-guest.png",
    moments: [
      { id: "vip-guest__prep-commute", label: "Prep & Commute", left: 5.495, top: 32.961, w: 16.0, h: 10.0 },
      { id: "vip-guest__arrival-access", label: "Arrival & Access", left: 31.534, top: 64.42, w: 16.0, h: 10.0 },
      { id: "vip-guest__private-lounge-entry", label: "Private Lounge Entry", left: 23.51, top: 82.722, w: 16.0, h: 10.0 },
      { id: "vip-guest__networking-event-time", label: "Networking & Event Time", left: 13.41, top: 81.324, w: 16.0, h: 10.0 },
      { id: "vip-guest__eat-drink", label: "Eat & Drink", left: 0.0, top: 86.349, w: 16.0, h: 10.0 },
      { id: "vip-guest__after-event", label: "After Event", left: 54.067, top: 62.471, w: 16.0, h: 10.0 },
    ],
  },
  "white-collar": {
    image: "/images/catalogue/assets/journeys/excel-maps/white-collar.png",
    moments: [
      { id: "white-collar__commute", label: "Commute", left: 0.0, top: 26.649, w: 16.0, h: 10.0 },
      { id: "white-collar__welcome-area", label: "Welcome Area", left: 30.27, top: 26.194, w: 16.0, h: 10.0 },
      { id: "white-collar__workplace", label: "Workplace", left: 38.433, top: 67.424, w: 16.0, h: 10.0 },
      { id: "white-collar__food-beverage-area", label: "Food & Beverage Area", left: 14.981, top: 80.156, w: 16.0, h: 10.0 },
      { id: "white-collar__wellbeing-breaktime", label: "Wellbeing & Breaktime", left: 4.397, top: 61.651, w: 16.0, h: 10.0 },
    ],
  },
};
