/** Auto-generated by scripts/ingest_personae_journey_excel.py — do not edit by hand. */

export const PERSONA_JOURNEYS_EXCEL: Record<
  string,
  {
    image: string;
    moments: Array<{ id: string; label: string; left: number; top: number; w: number; h: number }>;
  }
> = {
  "blue-collar": {
    image: "/images/catalogue/assets/journeys/iso-journey-work-blue-collar.svg",
    moments: [
      { id: "blue-collar__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "blue-collar__welcome-area", label: "Welcome Area", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "blue-collar__workplace", label: "Workplace", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "blue-collar__food-beverage-area", label: "Food & Beverage Area", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "blue-collar__wellbeing-breaktime", label: "Wellbeing & breaktime", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "client-heal": {
    image: "/images/catalogue/assets/journeys/iso-journey-client-operation-director.svg",
    moments: [
      { id: "client-heal__welcome-admission", label: "Welcome & Admission", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-heal__kick-off-early-check", label: "Kick off & Early Check", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-heal__internal-meetings-alignment", label: "Internal Meetings & Alignment", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-heal__service-review-site-rounds", label: "Service Review & Site Rounds", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-heal__lunch-stakeholder-engagement", label: "Lunch & Stakeholder Engagement", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-heal__improvement-sessions-forward-planning", label: "Improvement Sessions & Forward Planning", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "client-learn": {
    image: "/images/catalogue/assets/journeys/iso-journey-client-operation-director.svg",
    moments: [
      { id: "client-learn__welcome-admission", label: "Welcome & Admission", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-learn__kick-off-and-early-check", label: "Kick-off and Early Check", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-learn__internal-meetings-and-alignment", label: "Internal Meetings and Alignment", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-learn__service-review-and-site-rounds", label: "Service Review and Site Rounds", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-learn__lunch-stakeholders-engagement", label: "Lunch Stakeholders Engagement", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-learn__improvement-session-forward-planning", label: "Improvement Session & Forward Planning", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "client-play": {
    image: "/images/catalogue/assets/journeys/iso-journey-client-operation-director.svg",
    moments: [
      { id: "client-play__welcome-admission", label: "Welcome & Admission", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-play__kick-off-and-early-check", label: "Kick-off and Early Check", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-play__internal-meetings-and-alignment", label: "Internal Meetings and Alignment", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-play__service-review-and-site-rounds", label: "Service Review and Site Rounds", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-play__lunch-stakeholders-engagement", label: "Lunch Stakeholders Engagement", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-play__improvement-session-forward-planning", label: "Improvement Session & Forward Planning", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "client-work": {
    image: "/images/catalogue/assets/journeys/iso-journey-client-operation-director.svg",
    moments: [
      { id: "client-work__welcome-admission", label: "Welcome & Admission", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-work__kick-off-early-check", label: "Kick off & Early Check", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-work__internal-meetings-alignment", label: "Internal Meetings & Alignment", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-work__service-review-site-rounds", label: "Service Review & Site Rounds", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-work__lunch-stakeholder-engagement", label: "Lunch & Stakeholder Engagement", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "client-work__improvement-sessions-forward-planning", label: "Improvement Sessions & Forward Planning", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "doctor": {
    image: "/images/catalogue/assets/journeys/iso-journey-heal-doctor.svg",
    moments: [
      { id: "doctor__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "doctor__patient-consultations", label: "Patient Consultations", left: 15.333333333333336, top: 77.0, w: 16.0, h: 10.0 },
      { id: "doctor__team-meetings", label: "Team Meetings", left: 28.66666666666667, top: 77.0, w: 16.0, h: 10.0 },
      { id: "doctor__food-beverage-area", label: "Food & Beverage Area", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "doctor__breaktime", label: "Breaktime", left: 55.333333333333336, top: 77.0, w: 16.0, h: 10.0 },
      { id: "doctor__afternoon-rounds", label: "Afternoon Rounds", left: 68.66666666666667, top: 77.0, w: 16.0, h: 10.0 },
      { id: "doctor__end-of-shift", label: "End of Shift", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "grey-collar": {
    image: "/images/catalogue/assets/journeys/iso-journey-work-grey-collar.svg",
    moments: [
      { id: "grey-collar__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "grey-collar__welcome-area", label: "Welcome Area", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "grey-collar__workplace", label: "Workplace", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "grey-collar__food-beverage-area", label: "Food & Beverage Area", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "grey-collar__wellbeing-breaktime", label: "Wellbeing & Breaktime", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "military": {
    image: "/images/catalogue/assets/journeys/iso-journey-work-army-officer.svg",
    moments: [
      { id: "military__morning-routine", label: "Morning Routine", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "military__work-activities", label: "Work/Activities", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "military__lunch-break", label: "Lunch Break", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "military__afterwork", label: "Afterwork", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "military__dinner-with-regiment", label: "Dinner with Regiment", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "military__evening-routine", label: "Evening Routine", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "nurse": {
    image: "/images/catalogue/assets/journeys/iso-journey-heal-nurse.svg",
    moments: [
      { id: "nurse__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "nurse__welcome", label: "Welcome", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "nurse__nursing-care", label: "Nursing Care", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "nurse__food-beverage-area", label: "Food & Beverage Area", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "nurse__breaktime", label: "Breaktime", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "nurse__freetime-work-life-balance", label: "Freetime & Work/Life Balance", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "operator-heal": {
    image: "/images/catalogue/assets/journeys/iso-journey-operator-site-manager.svg",
    moments: [
      { id: "operator-heal__kick-off-early-check", label: "Kick-off & Early Check", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-heal__kitchen-back-kitchen-fm-checking-round", label: "Kitchen / Back Kitchen: FM Checking Round", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-heal__office-time", label: "Office Time", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-heal__food-beverage-area", label: "Food & Beverage Area", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-heal__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "operator-learn": {
    image: "/images/catalogue/assets/journeys/iso-journey-operator-site-manager.svg",
    moments: [
      { id: "operator-learn__kick-off-early-check", label: "Kick-off & Early Check", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-learn__kitchen-back-kitchen-fm-checking-round", label: "Kitchen/Back Kitchen: FM Checking Round", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-learn__office-time", label: "Office Time", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-learn__food-beverage-area", label: "Food & Beverage Area", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-learn__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "operator-play": {
    image: "/images/catalogue/assets/journeys/iso-journey-operator-site-manager.svg",
    moments: [
      { id: "operator-play__kick-off-early-check", label: "Kick-off & Early Check", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-play__kitchen-back-kitchen-fm-checking-round", label: "Kitchen/Back Kitchen: FM Checking Round", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-play__office-time", label: "Office Time", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-play__food-beverage-area", label: "Food & Beverage Area", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-play__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "operator-work": {
    image: "/images/catalogue/assets/journeys/iso-journey-operator-site-manager.svg",
    moments: [
      { id: "operator-work__kick-off-early-check", label: "Kick-off & Early Check", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-work__kitchen-back-kitchen-fm-checking-round", label: "Kitchen / Back Kitchen: FM Checking Round", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-work__office-time", label: "Office Time", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-work__food-beverage-area", label: "Food & Beverage Area", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "operator-work__order-planning-maintenance-management", label: "Order, Planning & Maintenance Management", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "parent": {
    image: "/images/catalogue/assets/journeys/iso-journey-learn-parent.svg",
    moments: [
      { id: "parent__prep-commute", label: "Prep & Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "parent__during-school-day", label: "During School Day", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "parent__meal-visibility", label: "Meal Visibility", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "parent__pick-up-time", label: "Pick-up Time", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "parent__evening-routine", label: "Evening Routine", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "parent__weekly-preparation", label: "Weekly Preparation", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "participant": {
    image: "/images/catalogue/assets/journeys/iso-journey-play-event-participant.svg",
    moments: [
      { id: "participant__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "participant__arrival-access", label: "Arrival & Access", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "participant__navigating-the-show", label: "Navigating the Show", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "participant__attending-a-talk-or-demo", label: "Attending a Talk or Demo", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "participant__networking-breaktime", label: "Networking & Breaktime", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "participant__after-event", label: "After Event", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "patient": {
    image: "/images/catalogue/assets/journeys/iso-journey-heal-patient.svg",
    moments: [
      { id: "patient__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "patient__welcome-and-admission", label: "Welcome and Admission", left: 15.333333333333336, top: 77.0, w: 16.0, h: 10.0 },
      { id: "patient__care-and-daily-routine", label: "Care and Daily Routine", left: 28.66666666666667, top: 77.0, w: 16.0, h: 10.0 },
      { id: "patient__snack", label: "Snack", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "patient__lunch-break", label: "Lunch Break", left: 55.333333333333336, top: 77.0, w: 16.0, h: 10.0 },
      { id: "patient__leaving-the-hospital", label: "Leaving the Hospital", left: 68.66666666666667, top: 77.0, w: 16.0, h: 10.0 },
      { id: "patient__rest-personal-balance", label: "Rest & Personal Balance", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "schoolchild": {
    image: "/images/catalogue/assets/journeys/iso-journey-learn-schoolchild.svg",
    moments: [
      { id: "schoolchild__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "schoolchild__welcome-at-school", label: "Welcome at School", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "schoolchild__in-class", label: "In Class", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "schoolchild__food-beverage-area", label: "Food & Beverage Area", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "schoolchild__freetime", label: "Freetime", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "senior": {
    image: "/images/catalogue/assets/journeys/iso-journey-heal-senior.svg",
    moments: [
      { id: "senior__welcome-residents", label: "Welcome Residents", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "senior__breakfast", label: "Breakfast", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "senior__activities", label: "Activities", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "senior__lunch-break", label: "Lunch Break", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "senior__breaktime", label: "Breaktime", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "senior__dinner", label: "Dinner", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "sport-fan": {
    image: "/images/catalogue/assets/journeys/sport-fan.jpg",
    moments: [
      { id: "sport-fan__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "sport-fan__welcome-area", label: "Welcome Area", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "sport-fan__waiting-for-the-game", label: "Waiting for the Game", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "sport-fan__social-time-match-time", label: "Social Time / Match Time", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "sport-fan__halftime-activities", label: "Halftime Activities", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "sport-fan__after-event", label: "After Event", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "student": {
    image: "/images/catalogue/assets/journeys/iso-journey-learn-student.svg",
    moments: [
      { id: "student__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "student__welcome-area", label: "Welcome Area", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "student__studies", label: "Studies", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "student__food-beverage-area", label: "Food & Beverage Area", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "student__freetime-studies-life-balance", label: "Freetime & Studies/Life Balance", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "teacher": {
    image: "/images/catalogue/assets/journeys/iso-journey-learn-teacher.svg",
    moments: [
      { id: "teacher__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "teacher__arrival-to-the-school-campus", label: "Arrival to the School / Campus", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "teacher__teaching", label: "Teaching", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "teacher__food-beverage-area", label: "Food & Beverage Area", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "teacher__freetime-work-life-balance", label: "Freetime & Work/Life Balance", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "tourist": {
    image: "/images/catalogue/assets/journeys/iso-journey-play-vip-guest-airport.svg",
    moments: [
      { id: "tourist__prep-commute", label: "Prep & Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "tourist__arrival-access", label: "Arrival & Access", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "tourist__eat-drink", label: "Eat & Drink", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "tourist__social-time-work", label: "Social time/Work", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "tourist__fast-access-to-gate", label: "Fast Access to Gate", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "vip-guest": {
    image: "/images/catalogue/assets/journeys/iso-journey-play-vip-guest-stadium.svg",
    moments: [
      { id: "vip-guest__prep-commute", label: "Prep & Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "vip-guest__arrival-access", label: "Arrival & Access", left: 18.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "vip-guest__private-lounge-entry", label: "Private Lounge Entry", left: 34.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "vip-guest__networking-event-time", label: "Networking & Event Time", left: 50.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "vip-guest__eat-drink", label: "Eat & Drink", left: 66.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "vip-guest__after-event", label: "After Event", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
  "white-collar": {
    image: "/images/catalogue/assets/journeys/iso-journey-work-white-collar.svg",
    moments: [
      { id: "white-collar__commute", label: "Commute", left: 2.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "white-collar__welcome-area", label: "Welcome Area", left: 22.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "white-collar__workplace", label: "Workplace", left: 42.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "white-collar__food-beverage-area", label: "Food & Beverage Area", left: 62.0, top: 77.0, w: 16.0, h: 10.0 },
      { id: "white-collar__wellbeing-breaktime", label: "Wellbeing & Breaktime", left: 82.0, top: 77.0, w: 16.0, h: 10.0 },
    ],
  },
};
